### ISSUE TITLE
Great God, the people call for your glory to return.

### ISSUE THREAD

**Issue by ednykissyou** [Wilenty/InnoSetup-Types-Components-Tasks-Run-Directly-In-the-code-#1]
Great God, the people call for your glory to return.
I think your Basic Runtime Libraries [HC] by Wilenty 2019-03-25_2 is really great.
I didn't know why it stopped.
The 2022 version does not seem to be available. It's a pity.
Can users customize the VC version?

**Comment by Wilenty** [comment]
-> https://github.com/Wilenty/VisualC-redist-installers-Demos/issues/2#issuecomment-2207768189
